version: '3.7'

services:
  php:
    restart: always
    build:
      context: .
    ports:
      - "9000:9000"
    env_file:
      - .env
    networks:
      - maker
    volumes:
    - ./bin:/app/bin
    - ./src:/app/src

networks:
  maker:
