<?php
use Birsoz\Converter\ArgumentType;
/* @var $writer \Birsoz\Converter\Writer\Dart */
/* @var $structs \Birsoz\Converter\Struct[] */

?>

<?php foreach ($structs as $struct): ?>
class <?= $struct->getClassName() ?> {

    <?php foreach ($struct->getArgs() as $arg): ?>
        <?= $writer->getDeclarationLine($arg); ?>

    <?php endforeach; ?>

    <?= $struct->getClassName() ?>({
        <?php foreach ($struct->getArgs() as $arg): ?>
            <?= $writer->getConstructorLine($arg); ?>

        <?php endforeach; ?>
    });

    factory <?= $struct->getClassName() ?>.fromJson(Map<String, dynamic> json) => new <?= $struct->getClassName() ?>(
        <?php foreach ($struct->getArgs() as $arg): ?>
            <?= $writer->getFactoryLine($arg); ?>

        <?php endforeach; ?>
    );

    Map<String, dynamic> toJson() => {
        <?php foreach ($struct->getArgs() as $arg): ?>
            <?= $writer->getToJsonLine($arg); ?>

        <?php endforeach; ?>
    };


    }
<?php endforeach;?>
